export type OrgUnitType =
    | "general"
    | "leadership"
    | "faculty"
    | "institute"
    | "centre"
    | "division"
    | "department"
    | "office"
    | "library";

export interface OrgUnit {
    id: string;
    name: string;
    shortLabel: string;
    type: OrgUnitType;
    campus?: "Kampar" | "Sungai Long" | "Both";
    website?: string;
    aliases: string[];
    fileStoreDisplayName: string;
    storeResourceIds: string[];
    enabledForChat: boolean;
    enabledForUpload: boolean;
    studentFacing: boolean;
}

export const ORG_UNITS: OrgUnit[] = [
    {
        id: "general",
        name: "General UTAR",
        shortLabel: "General",
        type: "general",
        website: "https://www.utar.edu.my/",
        aliases: ["general", "utar", "university", "main", "general utar"],
        fileStoreDisplayName: "UTAR General Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-general-knowledge-base-agtxfkmwqsz5"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    // Leadership / central offices
    {
        id: "president-office",
        name: "President's Office",
        shortLabel: "President's Office",
        type: "leadership",
        website: "https://pres.utar.edu.my/",
        aliases: ["president", "president office", "utar president", "ceo"],
        fileStoreDisplayName: "UTAR General Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-general-knowledge-base-agtxfkmwqsz5"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "vp-international-academic",
        name: "Office of VP (Internationalisation and Academic Development)",
        shortLabel: "VP IAD",
        type: "leadership",
        website: "https://iad.utar.edu.my/",
        aliases: ["vp internationalisation", "academic development", "internationalisation"],
        fileStoreDisplayName: "UTAR General Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-general-knowledge-base-agtxfkmwqsz5"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "vp-rd-commercialisation",
        name: "Office of VP (R & D and Commercialisation)",
        shortLabel: "VP R&D",
        type: "leadership",
        website: "https://rdc.utar.edu.my/",
        aliases: ["vp research", "commercialisation", "r&d", "research and development"],
        fileStoreDisplayName: "UTAR General Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-general-knowledge-base-agtxfkmwqsz5"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "vp-student-alumni",
        name: "Office of VP (Student Development and Alumni Relations)",
        shortLabel: "OVP SDAR",
        type: "leadership",
        website: "https://sdar.utar.edu.my/",
        aliases: ["student development", "alumni relations", "vp student", "sdar", "ovp sdar", "ovp-sdar"],
        fileStoreDisplayName: "UTAR OVP SDAR Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-ovp-sdar-knowledge-bas-fgmqtpmnkxo9"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "registrar",
        name: "Registrar's Office",
        shortLabel: "Registrar",
        type: "office",
        website: "https://rgo.utar.edu.my/",
        aliases: ["registrar", "registrar office", "student record", "academic record"],
        fileStoreDisplayName: "UTAR Registrar's Office Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-registrars-office-know-5izr1cyh46bh"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    // Key student service divisions
    {
        id: "dfn",
        name: "Division of Finance",
        shortLabel: "DFN",
        type: "division",
        website: "https://dfn.utar.edu.my/",
        aliases: ["dfn", "finance", "division of finance", "fees", "payment", "receipt", "invoice", "billing"],
        fileStoreDisplayName: "UTAR DFN Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dfn-knowledge-base-eqxkayxt9elw"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "deas",
        name: "Division of Examination and Awards",
        shortLabel: "DEAS",
        type: "division",
        website: "https://deas.utar.edu.my/",
        aliases: ["dea", "deas", "exam", "examination", "awards", "results", "exam timetable"],
        fileStoreDisplayName: "UTAR DEAS Knowledge Base",
        storeResourceIds: [
            "fileSearchStores/utar-deas-knowledge-base-lijnwpq485vr",
            "fileSearchStores/utar-dea-knowledge-base-vnkcqtpgrpql",
        ],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dace",
        name: "Division of Admissions and Credit Evaluation",
        shortLabel: "DACE",
        type: "division",
        website: "https://admission.utar.edu.my/",
        aliases: ["admission", "admissions", "credit evaluation", "dace", "entry requirement"],
        fileStoreDisplayName: "UTAR DACE Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dace-knowledge-base-7hvvd3v61wve"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dpp",
        name: "Division of Programme Promotion",
        shortLabel: "DPP",
        type: "division",
        website: "https://dpp.utar.edu.my/",
        aliases: ["programme promotion", "program promotion", "dpp", "marketing", "course promotion"],
        fileStoreDisplayName: "UTAR DPP Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dpp-knowledge-base-bt749926g3hp"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "library",
        name: "Library",
        shortLabel: "Library",
        type: "library",
        website: "https://library.utar.edu.my/",
        aliases: ["library", "utar library", "book", "database", "journal", "borrowing"],
        fileStoreDisplayName: "UTAR Library Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-library-knowledge-base-yk8ay1tecc7w"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "oia",
        name: "Office of International Affairs",
        shortLabel: "OIA",
        type: "office",
        website: "https://oia.utar.edu.my/",
        aliases: ["oia", "international affairs", "mobility", "exchange programme", "international collaboration"],
        fileStoreDisplayName: "UTAR OIA Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-oia-knowledge-base-l9qleqql83ze"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "diss",
        name: "Department of International Student Services",
        shortLabel: "DISS",
        type: "department",
        website: "https://diss.utar.edu.my/",
        aliases: ["international student", "international student services", "diss", "visa", "student pass"],
        fileStoreDisplayName: "UTAR DISS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-diss-knowledge-base-hwmbhalkmz6n"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "scholarships",
        name: "Department of Scholarships and Financial Aid",
        shortLabel: "Scholarships",
        type: "department",
        website: "https://dsfa.utar.edu.my/",
        aliases: ["dsfa", "scholarship", "scholarships", "financial aid", "loan", "bursary"],
        fileStoreDisplayName: "UTAR Scholarships Knowledge Base",
        storeResourceIds: [
            "fileSearchStores/utar-scholarships-knowledge-5fytwaxg9hdh",
            "fileSearchStores/utar-scholarships-knowledge-t039t24zgfd1",
        ],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    // Student affairs / campus services
    {
        id: "dsa-kampar",
        name: "Department of Student Affairs (Kampar Campus)",
        shortLabel: "DSA Kampar",
        type: "department",
        campus: "Kampar",
        website: "https://dsa.kpr.utar.edu.my/",
        aliases: ["dsa", "dsa kampar", "dsa kpr", "dsa-kpr", "dsakpr", "student affairs kampar", "student affairs", "student activity"],
        fileStoreDisplayName: "UTAR DSA Kampar Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dsa-kampar-knowledge-b-wesb1btx215v"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dsa-sungai-long",
        name: "Department of Student Affairs (Sungai Long Campus)",
        shortLabel: "DSA Sungai Long",
        type: "department",
        campus: "Sungai Long",
        website: "https://dsa.sl.utar.edu.my/",
        aliases: ["dsa", "dsa sungai long", "dsa sl", "dsa-sl", "dsasl", "student affairs sungai long", "student affairs"],
        fileStoreDisplayName: "UTAR DSA Sungai Long Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dsa-sungai-long-knowle-7snk1jqydjua"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dssc",
        name: "Department of Soft Skills Competency (Sungai Long & Kampar Campuses)",
        shortLabel: "DSSC",
        type: "department",
        campus: "Both",
        website: "https://softskill.utar.edu.my/",
        aliases: [
            "dssc",
            "ussdc",
            "soft skills",
            "soft skills competency",
            "soft skill",
            "soft skill points",
            "utar care",
            "utar lead",
            "talent programme",
            "volunteer",
            "community engagement",
        ],
        fileStoreDisplayName: "UTAR DSSC Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dssc-knowledge-base-36okwh6msr3z"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    // Facilities / safety / services
    {
        id: "def-kampar",
        name: "Department of Estates and Facilities (Kampar Campus)",
        shortLabel: "DEF Kampar",
        type: "department",
        campus: "Kampar",
        aliases: ["estate kampar", "facilities kampar", "def kampar", "maintenance kampar"],
        fileStoreDisplayName: "UTAR DEF Kampar Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-def-kampar-knowledge-b-t46ex69v3vpn"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "def-sungai-long",
        name: "Department of Estates and Facilities (Sungai Long Campus)",
        shortLabel: "DEF Sungai Long",
        type: "department",
        campus: "Sungai Long",
        website: "https://def.sl.utar.edu.my/",
        aliases: ["estate sungai long", "facilities sungai long", "def sungai long", "maintenance sungai long"],
        fileStoreDisplayName: "UTAR DEF Sungai Long Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-def-sungai-long-knowle-7icjf53ioq9v"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dss-kampar",
        name: "Department of Safety and Security (Kampar Campus)",
        shortLabel: "DSS Kampar",
        type: "department",
        campus: "Kampar",
        website: "https://dss.kpr.utar.edu.my/",
        aliases: ["dss", "dss kampar", "dss kpr", "dss-kpr", "dsskpr", "security kampar", "safety kampar", "emergency kampar", "safety and security"],
        fileStoreDisplayName: "UTAR DSS Kampar Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dss-kampar-knowledge-b-fcwlqbazfbfr"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dss-sungai-long",
        name: "Department of Safety and Security (Sungai Long Campus)",
        shortLabel: "DSS Sungai Long",
        type: "department",
        campus: "Sungai Long",
        website: "https://dss.sl.utar.edu.my/",
        aliases: ["dss", "dss response...", "dss", "dss sungai long", "dss sl", "dss-sl", "dsssl", "security sungai long", "safety sungai long", "emergency sungai long", "safety and security"],
        fileStoreDisplayName: "UTAR DSS Sungai Long Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dss-sungai-long-knowle-yz7951nccegk"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dgs-kampar",
        name: "Department of General Services (Kampar Campus)",
        shortLabel: "DGS Kampar",
        type: "department",
        campus: "Kampar",
        website: "https://dgs.kpr.utar.edu.my/",
        aliases: ["dgs kampar", "general services kampar", "kampar bus", "kampar bus schedule", "kampar shuttle bus", "kampar bus service"],
        fileStoreDisplayName: "UTAR DGS Kampar Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dgs-kampar-kb-clean-gtf58bd38zr9"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dgs-sungai-long",
        name: "Department of General Services (Sungai Long Campus)",
        shortLabel: "DGS Sungai Long",
        type: "department",
        campus: "Sungai Long",
        website: "https://dgs.sl.utar.edu.my/",
        aliases: ["dgs response...", "dgs", "dgs sungai long", "general services response...", "general services sungai long", "sungai long bus", "sungai long bus schedule", "sungai long shuttle bus", "sungai long bus service", "sl bus"],
        fileStoreDisplayName: "UTAR DGS Sungai Long Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dgs-sungai-long-knowle-6pqh2bbtrmoy"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    // More admin / technical support units
    {
        id: "dhr",
        name: "Division of Human Resource",
        shortLabel: "DHR",
        type: "division",
        website: "https://hr.utar.edu.my/",
        aliases: ["dhr", "human resource", "human resources", "hr", "staff matters", "employment"],
        fileStoreDisplayName: "UTAR DHR Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dhr-knowledge-base-ugjsmwgrlwfl"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "dssm",
        name: "Division of Sustainability and Strategic Management",
        shortLabel: "DSSM",
        type: "division",
        website: "https://dssm.utar.edu.my/",
        aliases: ["dssm", "sustainability and strategic management", "sustainability", "strategic management"],
        fileStoreDisplayName: "UTAR DSSM Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dssm-knowledge-base-gx2xveipisxl"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "itisc",
        name: "IT Infrastructure and Support Centre",
        shortLabel: "ITISC",
        type: "centre",
        website: "https://itisc.utar.edu.my/",
        aliases: ["itisc", "it support", "wifi", "network", "internet", "utar portal", "wble"],
        fileStoreDisplayName: "UTAR ITISC Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-itisc-knowledge-base-0bmz3znho538"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "csds",
        name: "Centre for Software Development and Support",
        shortLabel: "CSDS",
        type: "centre",
        website: "https://csds.utar.edu.my/",
        aliases: ["csds", "software support", "system support", "application support"],
        fileStoreDisplayName: "UTAR CSDS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-csds-knowledge-base-6w0vpl5q1ann"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "cmps",
        name: "Centre for Multimedia Production and Services",
        shortLabel: "CMPS",
        type: "centre",
        website: "https://cmps.utar.edu.my/",
        aliases: ["cmps", "multimedia production", "video production", "media service"],
        fileStoreDisplayName: "UTAR CMPS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-cmps-knowledge-base-29fxs7ytnedb"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },

    // Faculties / institutes / centres
    {
        id: "fmhs",
        name: "M. Kandiah Faculty of Medicine and Health Sciences",
        shortLabel: "FMHS",
        type: "faculty",
        campus: "Sungai Long",
        website: "https://fmhs.utar.edu.my/",
        aliases: ["fmhs", "medicine", "health sciences", "m kandiah faculty"],
        fileStoreDisplayName: "UTAR FMHS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-mk-fmhs-knowledge-base-6gvcn05lypq1"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "lkcfes",
        name: "Lee Kong Chian Faculty of Engineering and Science",
        shortLabel: "LKC FES",
        type: "faculty",
        website: "https://lkcfes.utar.edu.my/",
        aliases: ["lkc fes", "lkcfes", "lee kong chian", "engineering and science"],
        fileStoreDisplayName: "UTAR LKC FES Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-lkc-fes-knowledge-base-lcc3ps6w9knv"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fegt",
        name: "Faculty of Engineering and Green Technology",
        shortLabel: "FEGT",
        type: "faculty",
        website: "https://fegt.utar.edu.my/",
        aliases: ["fegt", "engineering and green technology", "green technology"],
        fileStoreDisplayName: "UTAR FEGT Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fegt-knowledge-base-of5dlthl7bna"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fict",
        name: "Faculty of Information and Communication Technology",
        shortLabel: "FICT",
        type: "faculty",
        website: "https://fict.utar.edu.my/",
        aliases: ["fict", "ict", "information and communication technology", "computer science", "software engineering"],
        fileStoreDisplayName: "UTAR FICT Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fict-knowledge-base-jqyarv623c7t"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fsc",
        name: "Faculty of Science",
        shortLabel: "FSc",
        type: "faculty",
        website: "https://fsc.utar.edu.my/",
        aliases: ["fsc", "faculty of science", "science faculty"],
        fileStoreDisplayName: "UTAR FSc Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fsc-knowledge-base-g4ogcu38qyzb"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fam",
        name: "Faculty of Accountancy and Management",
        shortLabel: "FAM",
        type: "faculty",
        campus: "Sungai Long",
        website: "https://fam.utar.edu.my/",
        aliases: ["fam", "accountancy and management", "accounting faculty", "management faculty"],
        fileStoreDisplayName: "UTAR FAM Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fam-knowledge-base-7uoqp4p7u625"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fbf",
        name: "Teh Hong Piow Faculty of Business and Finance",
        shortLabel: "THP FBF",
        type: "faculty",
        campus: "Kampar",
        website: "https://fbf.utar.edu.my/",
        aliases: ["fbf", "thp fbf", "thpfbf", "business and finance", "teh hong piow", "business faculty", "finance faculty"],
        fileStoreDisplayName: "UTAR THP FBF Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fbf-knowledge-base-7wz1lu34rexv"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fass",
        name: "Faculty of Arts and Social Science",
        shortLabel: "FAS",
        type: "faculty",
        campus: "Kampar",
        website: "https://fas.utar.edu.my/",
        aliases: ["fas", "fass", "arts and social science", "social science"],
        fileStoreDisplayName: "UTAR FAS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fass-knowledge-base-kuhhy0pikxa3"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fci",
        name: "Faculty of Creative Industries",
        shortLabel: "FCI",
        type: "faculty",
        website: "https://fci.utar.edu.my/",
        aliases: ["fci", "creative industries", "creative industry"],
        fileStoreDisplayName: "UTAR FCI Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fci-knowledge-base-4v4z72kobkb1"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fcs",
        name: "Faculty of Chinese Studies",
        shortLabel: "FCS",
        type: "faculty",
        website: "https://fcs.utar.edu.my/",
        aliases: ["fcs", "chinese studies", "faculty of chinese studies"],
        fileStoreDisplayName: "UTAR FCS Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fcs-knowledge-base-w8bbtf26963v"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "fed",
        name: "Faculty of Education",
        shortLabel: "FED",
        type: "faculty",
        website: "https://fed.utar.edu.my/",
        aliases: ["fed", "education faculty", "faculty of education"],
        fileStoreDisplayName: "UTAR FED Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-fed-knowledge-base-k4gxu1g6ejek"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "ipsr",
        name: "Institute of Postgraduate Studies & Research",
        shortLabel: "IPSR",
        type: "institute",
        website: "https://ipsr.utar.edu.my/",
        aliases: ["ipsr", "postgraduate", "postgraduate studies", "research", "thesis", "grant", "publication support"],
        fileStoreDisplayName: "UTAR IPSR Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-ipsr-knowledge-base-opnxxgqxlhme"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "imd",
        name: "Institute of Management and Leadership Development",
        shortLabel: "IMLD",
        type: "institute",
        website: "https://imld.utar.edu.my/",
        aliases: ["imld", "management and leadership development", "leadership development"],
        fileStoreDisplayName: "UTAR IMLD Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-imld-knowledge-base-jorlul8coqjg"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "cfs-kampar",
        name: "Centre for Foundation Studies (Kampar Campus)",
        shortLabel: "CFS Kampar",
        type: "centre",
        campus: "Kampar",
        website: "https://cfs.kpr.utar.edu.my/",
        aliases: ["cfs kampar", "foundation kampar", "centre for foundation studies kampar"],
        fileStoreDisplayName: "UTAR CFS Kampar Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-cfs-kampar-knowledge-b-2ysyytxyhdiz"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "cfs-sungai-long",
        name: "Centre for Foundation Studies (Sungai Long Campus)",
        shortLabel: "CFS Sungai Long",
        type: "centre",
        campus: "Sungai Long",
        website: "https://cfs.sl.utar.edu.my/",
        aliases: ["cfs", "cfs sungai long", "foundation sungai long", "centre for foundation studies sungai long"],
        fileStoreDisplayName: "UTAR CFS Sungai Long Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-cfs-sungai-long-knowle-2nks0zhsqeck"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "iie",
        name: "Institute of International Education",
        shortLabel: "IIE",
        type: "institute",
        website: "https://iie.utar.edu.my/",
        aliases: ["iie", "international education", "institute of international education"],
        fileStoreDisplayName: "UTAR IIE Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-iie-knowledge-base-ltc0m3y8e56b"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "cccd",
        name: "Centre for Corporate and Community Development",
        shortLabel: "CCCD",
        type: "centre",
        website: "https://cccd.utar.edu.my/",
        aliases: ["cccd", "corporate and community development", "community development"],
        fileStoreDisplayName: "UTAR CCCD Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-cccd-knowledge-base-i9dj5t2c4aqc"],
        enabledForChat: false,
        enabledForUpload: true,
        studentFacing: false,
    },
    {
        id: "confucius",
        name: "Confucius Institute",
        shortLabel: "Confucius Institute",
        type: "institute",
        website: "https://ci.utar.edu.my/",
        aliases: ["confucius", "confucius institute", "chinese language"],
        fileStoreDisplayName: "UTAR Confucius Institute Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-confucius-institute-kn-y9u4zm2gpt09"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },

    {
        id: "darp",
        name: "Department of Alumni Relations and Placement",
        shortLabel: "DARP",
        type: "department",
        website: "https://alumni.utar.edu.my/",
        aliases: [
            "darp",
            "alumni relations",
            "placement",
            "career placement",
            "internship",
            "industrial training",
            "job placement",
            "career",
            "employability",
            "job search"
        ],
        fileStoreDisplayName: "UTAR DARP Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-darp-knowledge-base-8lt0475tvcig"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
    {
        id: "dice",
        name: "Department of Innovation & Commercialisation",
        shortLabel: "DICE",
        type: "department",
        website: "https://dice.utar.edu.my/",
        aliases: ["dice", "innovation", "commercialisation", "unovate", "unovate centre", "utaryess"],
        fileStoreDisplayName: "UTAR DICE Knowledge Base",
        storeResourceIds: ["fileSearchStores/utar-dice-knowledge-base-tnzzlpte9nap"],
        enabledForChat: true,
        enabledForUpload: true,
        studentFacing: true,
    },
];

export function getOrgUnitById(id?: string): OrgUnit {
    return ORG_UNITS.find((unit) => unit.id === id) || ORG_UNITS[0];
}

export function getChatEnabledOrgUnits(): OrgUnit[] {
    return ORG_UNITS.filter((unit) => unit.enabledForChat);
}

export function getUploadEnabledOrgUnits(): OrgUnit[] {
    return ORG_UNITS.filter((unit) => unit.enabledForUpload);
}

function escapeRegex(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function findOrgUnitByAlias(text: string): OrgUnit | null {
    const lower = text.toLowerCase().trim();

    return (
        ORG_UNITS.find((unit) =>
            unit.aliases.some((alias) => {
                const aliasLower = alias.toLowerCase().trim();

                if (!aliasLower) return false;

                // Exact match is always allowed.
                if (lower === aliasLower) return true;

                // Short aliases such as DEA, DFN, FBF, FICT must match as whole words only.
                // This prevents "dean" from matching "dea".
                if (aliasLower.length <= 4) {
                    const wordRegex = new RegExp(`\\b${escapeRegex(aliasLower)}\\b`, "i");
                    return wordRegex.test(lower);
                }

                // Longer aliases can match as phrases, but still on word boundaries.
                const phraseRegex = new RegExp(`\\b${escapeRegex(aliasLower)}\\b`, "i");
                return phraseRegex.test(lower);
            })
        ) || null
    );
}